config/routes.rb
Rails.application.routes.draw do
  get 'playlist_calculator/time'

  get 'playlist_calculator/playlist'

  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
	def self.create_playlist(total_duration)
		tempo_restante = total_duration
		playlist = []
		todas_embaralhadas = Song.all.shuffle

		# ushdiuhsdiauhsdiahd
		while tempo_restante > 0 && todas_embaralhadas.size > 0
			song = todas_embaralhadas.shift
			playlist << song

			tempo_restante = tempo_restante - song.duration
		end

		return playlist
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_calculator_controller.rb
class PlaylistCalculatorController < ApplicationController
  def time
  end

  def playlist
  	@time = params[:time].to_i
  	@songs = Song.create_playlist(@time * 60)

=begin
	@total_playlist = 0
  	@songs.each do |song|
  		@total_playlist = @total_playlist + song.duration
  	end
=end

  	@total_playlist = @songs.map{|song| song.duration }.sum
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :duration, :artist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlist_calculator_helper.rb
module PlaylistCalculatorHelper
	def format_seconds(seconds)
		num_minutes = seconds / 60
		num_seconds = seconds % 60

		return format("%02d:%02d", num_minutes, num_seconds)
	end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cronomusic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlist_calculator/playlist.html.erb
<h1>Sua playlist de <%= @time %> minutos ficou 
	com <%= format_seconds(@total_playlist) %></h1>

<ul>
<% @songs.each do |song| %>
  <li><%= song.name %> <%= format_seconds(song.duration) %> <%= song.artist %>
  </li>
<% end %>
</ul>

<%= link_to('Voltar', "/playlist_calculator/time") %>

app/views/playlist_calculator/time.html.erb
<h1>Bem vindo ao Cronomusic!</h1>
<h3>Faca playlists no tempo certo</h3>
<p>Nao esqueca de digitar em minutos</p>

<!--
<%= form_tag("/playlist_calculator/playlist") do %>
  <%= text_field_tag('time') %>
  <%= button_tag('Criar playlist') %>
<% end %>
-->

<form action="/playlist_calculator/playlist">
	<input type="number" name="time"/>
	<button>Criar playlist</button>
</form>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th>Musica</th>
      <th>Duracao</th>
      <th>Artista</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.duration %></td>
        <td><%= song.artist %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @song.duration %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>